# _config.yml

title: "Deprecated Software Engineer"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"

# Define collections
collections_dir: series

collections:
  cpp20_guides:
    sort_by: id
  guides:
    output: true
    permalink: /:collection/:path/

 
author:
  name: "RNDr. Šimon Tóth"
  avatar: "/assets/images/bio-photo.png"
  bio: "ex-Software Egineer, ex-Researcher."
  location: "Brno, Czech Republic"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/happycerberus"
    - label: "Medium"
      icon: "fab fa-medium-m"
      url: "https://medium.com/@happy.cerberus"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/c/SimonToth"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/simontoth/"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/SimonToth83"
    - label: "Business Contact"
      url: "mailto:business@simontoth.eu"

include: [CNAME]