# _config.yml



# Site configuration
title: "Deprecated Software Engineer"
name: "RNDr. Šimon Tóth"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-include-cache
description: "I create educational content around software engineering and backend programming languages."
url: "simontoth.eu"
repository: "happycerberus/happycerberus.github.io"
atom_feed:
  hide: true
footer_scripts:
  - "https://kit.fontawesome.com/09f80d5d35.js"


# Content & collections configuration
collections_dir: series

collections:
  cpp20_guides:
    sort_by: id
  guides:
    output: true
    permalink: /:collection/:path/

# Social media links
author:
  name: "RNDr. Šimon Tóth"
  avatar: "/assets/images/profile-small-square.webp"
  bio: "ex-Software Egineer, ex-Researcher."
  location: "Brno, Czech Republic"
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github fa-fw"
      url: "https://github.com/happycerberus"
    - label: "Medium"
      icon: "fa-brands fa-medium fa-fw"
      url: "https://medium.com/@simontoth"
    - label: "YouTube"
      icon: "fa-brands fa-youtube fa-fw"
      url: "https://www.youtube.com/c/SimonToth"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin fa-fw"
      url: "https://www.linkedin.com/in/simontoth/"
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon fa-fw"
      url: "https://hachyderm.io/@simontoth"
    - label: "Business Contact"
      icon: "fa-solid fa-at fa-fw"
      url: "mailto:business@simontoth.eu"

include: [CNAME, downloads]
