name: Build and deploy Jekyll site to GitHub Pages

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 9 * * *      
  # Allow manual trigger.
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.PAGES_TOKEN }}
          target_branch: gh-pages
