name: Fetch RSS feeds for Substack

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  # Allow manual trigger.
  workflow_dispatch:
    

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://simontoth.substack.com/feed"
          readme_path: "./index.md"