name: Fetch RSS feeds for Youtube & Medium

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  # Allow manual trigger.
  workflow_dispatch:
    

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://medium.com/feed/@simontoth
          readme-section: medium
          branch: main
          path: index.md
          template: "<li><a href=\"{{ link }}\">{{ title }}</a></li>"
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://www.youtube.com/feeds/videos.xml?channel_id=UCpSqMoRM5sewrjtI1RkDKxg
          readme-section: youtube
          branch: main
          path: index.md
          template: "<li><a href=\"{{ link }}\">{{ title }}</a></li>"
          
